### ISSUE TITLE
Site.conf

### ISSUE THREAD

**Issue by Gimmo** [systemroot/ogars-bots-blocker#3]
What is site.conf and what for it present in project?

**Comment by systemroot** [comment]
site.conf handle some rules, and they are for nginx, idk if you have use nginx before, but if yes i think you will understand, 

with other words, (talking about ubuntu 14.04)
you can do **"apt-get install nginx -y; service nginx start"** , // Make sure apache or anything else isn't running on port :80, after nginx installation visit your ip you will see nginx default page, rules which tell nginx where is ex public_html/, or where to get files for default index page are into 
/etc/nginx/sites-available/default  <- you can open dat and you will see some rules like site.conf . 
so you can copy all code into site.conf and place them into "default" (/etc/nginx/sites-available/default make sure you delete old code) then you can edit rules however you want and change ports about where is your server running, 

site.conf extactly do port forward, example you will connect server on port 61, (but private server port is 45128) so when you will try to connect on port 61 nginx will run those rules, example disallow multiple ip's, or useragents etc, and if detect something nginx will not allow you to connect on server...
but don't forget do set nginx up in right way, Here i'm wroting a simple installation tut.

`apt-get update -y; apt-get upgrade -y;`
`service apache2 stop`
`apt-get install nginx -y`

`cd /home; git clone https://github.com/Megabyte918/MultiOgar-Edited.git`
`cd MultiOgar-Edited/src/; npm install`
`nano gameserver.ini`
All we know port 443 is default and if someone will try to add minions in your server they'll try that port :443
so change serverPort = 443, to something like **serverPort = 45128**

now you need to set up nginx, 
`cd /etc/nginx/sites-available/; ls`
open that **default** with **nano** or **vim** or with whatever u want
delete all what is into it and copy/paste those https://raw.githubusercontent.com/systemroot/ogars-bots-blocker/master/site.conf

now you will see 
``#Server Public Port.``
``listen             61;``
i call this "Public port" because on this port you will connect! so wrote what you want, 
and change this
``
proxy_pass          http://localhost:443;
``
if you wrote **serverPort = 45128** in gameserver.ini then that should be 
``
proxy_pass          http://localhost:45128;
``

now save **default** file,

and you will need to set limit per ip, and country deny,
so
`cd /etc/nginx/; rm -Rf nginx.conf`
`wget https://raw.githubusercontent.com/systemroot/ogars-bots-blocker/master/etc/nginx/nginx.conf`
``apt-get install geoip-database libgeoip1 -y``
``mv /usr/share/GeoIP/GeoIP.dat /usr/share/GeoIP/GeoIP.dat_bak``
``cd /usr/share/GeoIP/``
``wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz``
``gunzip GeoIP.dat.gz``



`service nginx restart`

go into /home/Multiogar-edited/src start server and connect it to **ws://IP:61**

**Comment by Gimmo** [comment]
But why ubuntu-mmode.sh have different settings?
```
echo '
server {
        listen             ppub;
        server_name        domainn;
        access_log /var/log/nginx/monitor_log combined;
        location / {
        if ($http_user_agent ~ "WOW64" ) {
           set $browser-version outdated;
        }
        if ($http_user_agent ~ "rv:30.0" ) {
           set $browser-version outdated;
        }
        if ($http_user_agent ~ "Firefox/30.0" ) {
           set $browser-version outdated;
        }
        if ($browser-version = outdated) {
           return 444;
        }
        access_log /var/log/nginx/monitor_log combined;
        proxy_pass         http://localhost:srvpp;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   Host $host;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection "upgrade";
        }
}
' > /etc/nginx/sites-enabled/default
```
Which variant is closer to real life or which is just a sample?

**Comment by systemroot** [comment]
@Gimmo because i can't add site.conf on it. because when you execute a bash script to create your default file sometimes bash script will fail and i need to replace too much lines, 
so take it as a old version, that on ubuntu-mmode.sh, will just block polarsbots, 
you can copy and paste last version from site.conf

**Comment by Gimmo** [comment]
I understand now. Thanks, I'll try.

**Comment by systemroot** [comment]
np, let me to know if there is a problem, or if anyone is still able to add bot's on your server, because as u can see only i have test those https://github.com/systemroot/ogars-bots-blocker/issues/1

feel free to re'open if is needed!
